# coding: utf-8

"""
    InsightsServices-Dev-QA

    SR Insight Service API Documentation  # noqa: E501

    OpenAPI spec version: 3.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import insights_plotrisk
from insights_plotrisk.models.multi_polygon import MultiPolygon  # noqa: E501
from insights_plotrisk.rest import ApiException


class TestMultiPolygon(unittest.TestCase):
    """MultiPolygon unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiPolygon(self):
        """Test MultiPolygon"""
        # FIXME: construct object with mandatory attributes with example values
        # model = insights_plotrisk.models.multi_polygon.MultiPolygon()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
